version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nasa-api
    restart: always
    ports:
      - "3400:8000"
    networks:
      - nasa-network

networks:
  nasa-network:
    driver: bridge
