version: '4.1'

services:
  # NASA API service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nasa-api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    networks:
      - nasa-network

networks:
  nasa-network:
    driver: bridge
