name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:
  
    runs-on: self-hosted

    steps:
    - name: Pull docker image
      run: sudo docker pull samthemaverick/nasa-project1:latest
    - name: Delete the old Docker container
      run: sudo docker rm -f nasa-project1-container || true
    - name: Run Docker container
      run: sudo docker run -d -p 8000:8000 --restart=always --name nasa-project1-container samthemaverick/nasaproject1
