name: NASA Project CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    env: 
      CI: true
      MONGO_URL: mongodb://localhost/nasa
    strategy:
      matrix:
        node-version: [ 17.x, 18.x]
        mongodb-version: [ 4.4 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use MOngoDB from GitHub actions
        uses: supercharge/mongodb-github-action@v1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm install
      - run: npm run build --prefix client
      - run: npm test
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS EC2 instance
      uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull the latest Docker image
            docker pull samthemaverick/nasa-project

            # Stop and remove the existing container
            docker stop samthemaverick/nasa-project || true
            docker rm samthemaverick/nasa-project || true

            # Run the new Docker container
            docker run -d --restart=always --name nasa-project -p 8000:8000 your-docker-image:tag
        

      